# Generated by Django 4.2.3 on 2023-07-26 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crystal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('hardness', models.IntegerField()),
                ('structure', models.CharField(max_length=50)),
            ],
        ),
    ]
