# Generated by Django 4.2.3 on 2023-07-27 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_crystal_color_crystal_transparency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crystal',
            name='color',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Aquired',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=50)),
                ('crystal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.crystal')),
            ],
        ),
    ]
