# Generated by Django 4.2.3 on 2023-07-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_crystal_color_aquired'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='aquired',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='aquired',
            name='date',
            field=models.DateField(verbose_name='Date Aquired'),
        ),
    ]
